package com.github.simy4.poc.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersioned;
import com.github.simy4.poc.model.converters.DynamoDBTypeConvertedInstant;
import com.github.simy4.poc.model.generators.DynamoDBAutoGeneratedInstant;
import org.immutables.value.Value;

@Value.Style(
    stagedBuilder = true,
    jdkOnly = true,
    get = {"get*", "is*"},
    create = "new",
    beanFriendlyModifiables = true,
    isInitialized = "wasInitialized",
    passAnnotations = {
      DynamoDBTable.class,
      DynamoDBIgnore.class,
      DynamoDBHashKey.class,
      DynamoDBRangeKey.class,
      DynamoDBDocument.class,
      DynamoDBVersioned.class,
      DynamoDBAttribute.class,
      DynamoDBAutoGeneratedKey.class,
      DynamoDBTypeConvertedInstant.class,
      DynamoDBAutoGeneratedInstant.class,
    })
public @interface Data {}
