package com.github.simy4.poc.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.immutables.value.Value;

@Value.Style(
    jdkOnly = true,
    get = {"get*", "is*"},
    create = "new",
    beanFriendlyModifiables = true,
    isInitialized = "wasInitialized",
    passAnnotations = {
      DynamoDBTable.class,
      DynamoDBHashKey.class,
      DynamoDBRangeKey.class,
      DynamoDBIgnore.class,
      DynamoDBAttribute.class,
      DynamoDBAutoGeneratedKey.class
    },
    defaults = @Value.Immutable(copy = false))
public @interface Data {}
