package com.github.simy4.poc.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.github.simy4.poc.model.converters.DynamoDBTypeConvertedInstant;
import com.github.simy4.poc.model.generators.DynamoDBAutoGeneratedInstant;
import org.immutables.value.Value;
import org.springframework.lang.Nullable;

import java.time.Instant;
import java.util.Optional;

@Data
@Value.Immutable
@Value.Modifiable
@DynamoDBTable(tableName = "${db.entities.table-name}")
@JsonDeserialize(as = ImmutableEntity.class)
public interface Entity extends Identifiable {
  String PK_PREFIX = "Entity#";

  static Identity id(String sk) {
    return ImmutableIdentity.of(PK_PREFIX, sk);
  }

  @Override
  @DynamoDBHashKey
  @Value.Default
  default String getPk() {
    return PK_PREFIX;
  }

  String getName();

  @Nullable
  @DynamoDBAutoGeneratedInstant
  @DynamoDBTypeConvertedInstant
  Instant getUpdated();

  @Value.Default
  @DynamoDBTypeConvertedInstant
  default Instant getCreated() {
    return Instant.now();
  }

  default Entity patch(UpdateEntity entity) {
    return ImmutableEntity.builder()
        .from(this)
        .name(Optional.ofNullable(entity.getName()).orElseGet(this::getName))
        .build();
  }
}
