package com.github.simy4.poc.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import org.springframework.lang.Nullable;

public interface Identifiable {
  Identity getId();

  @DynamoDBHashKey
  String getPk();

  @DynamoDBRangeKey
  @DynamoDBAutoGeneratedKey
  @Nullable String getSk();
}
