package com.github.simy4.poc.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.springframework.lang.Nullable;

public interface Identifiable {
  @JsonIgnore
  @DynamoDBIgnore
  default Identity getId() {
    return ImmutableIdentity.of(getPk(), getSk());
  }

  @DynamoDBHashKey
  String getPk();

  @DynamoDBRangeKey
  @DynamoDBAutoGeneratedKey
  @Nullable
  String getSk();
}
