#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Docker On Linux 

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *' # Everyday at 1

jobs:
  windows:
    name: Linux 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install Docker Maven Plugin
        run: |
          git clone https://github.com/ncelerier/docker-maven-plugin
          cd docker-maven-plugin
          mvn -f pom.xml -B -DskipTests clean install
          cd ..
      - name: Install and Run Integration Tests
        run: |
          mvn clean install -DskipTests
          mvn docker:build
          mvn docker:start
