package com.github.simy4.poc.model.generators;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerator;
import org.junit.jupiter.api.Test;

import java.lang.annotation.Annotation;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneId;

import static org.junit.jupiter.api.Assertions.assertEquals;

class DynamoDBAutoGeneratedInstantTest {
  private final DynamoDBAutoGenerator<Instant> autoGenerator =
      new DynamoDBAutoGeneratedInstant.Generator(
          Clock.fixed(Instant.EPOCH, ZoneId.of("UTC")),
          new DynamoDBAutoGeneratedInstant() {
            @Override
            public DynamoDBAutoGenerateStrategy strategy() {
              return DynamoDBAutoGenerateStrategy.ALWAYS;
            }

            @Override
            public Class<? extends Annotation> annotationType() {
              return DynamoDBAutoGeneratedInstant.class;
            }
          });

  @Test
  void shouldGenerate() {
    assertEquals(Instant.EPOCH, autoGenerator.generate(Instant.EPOCH));
  }
}
